import { defineConfig } from 'vitepress'

const generalSidebar = [
  {
    text: 'AIPs by Scope',
    items: [
      { text: 'General', link: '/aip/general' },
      { text: 'Google Cloud Platform', link: 'https://google.aip.dev/cloud' },
      { text: 'Auth', link: 'https://google.aip.dev/auth' },
      { text: 'Client libraries', link: 'https://google.aip.dev/client-libraries' },
      { text: 'Workspace', link: 'https://google.aip.dev/apps' },
      { text: 'Actions on Google', link: 'https://google.aip.dev/aog' },
    ],
  },
  {
    text: 'AIPs',
    collapsed: false,
    items: [
      { text: '1. AIP 的目的与指南', link: '/aip/general/0001_zh' },
      { text: '2. AIP 编号', link: '/aip/general/0002_zh' },
      { text: '3. AIP 版本管理', link: '/aip/general/0003_zh' },
      { text: '200. 先例', link: '/aip/general/0200_zh' },
      { text: '8. AIP 风格与指导', link: '/aip/general/0008_zh' },
      { text: '9. 术语表', link: '/aip/general/0009_zh' },
      { text: '100. API 设计评审常见问题', link: '/aip/general/0100_zh' },
      { text: '111. 平面', link: '/aip/general/0111_zh' },
      { text: '121. 面向资源的设计', link: '/aip/general/0121_zh' },
      { text: '122. 资源名称', link: '/aip/general/0122_zh' },
      { text: '123. 资源类型', link: '/aip/general/0123_zh' },
      { text: '124. 资源关联', link: '/aip/general/0124_zh' },
      { text: '126. 枚举', link: '/aip/general/0126_zh' },
      { text: '127. HTTP 与 gRPC 转码', link: '/aip/general/0127_zh' },
      { text: '128. 声明式友好的接口', link: '/aip/general/0128_zh' },
      { text: '129. 服务端修改值与默认值', link: '/aip/general/0129_zh' },
      { text: '130. 方法', link: '/aip/general/0130_zh' },
      { text: '131. 标准方法：Get', link: '/aip/general/0131_zh' },
      { text: '132. 标准方法：List', link: '/aip/general/0132_zh' },
      { text: '133. 标准方法：Create', link: '/aip/general/0133_zh' },
      { text: '134. 标准方法：Update', link: '/aip/general/0134_zh' },
      { text: '135. 标准方法：Delete', link: '/aip/general/0135_zh' },
      { text: '136. 自定义方法', link: '/aip/general/0136_zh' },
      { text: '140. 字段名称', link: '/aip/general/0140_zh' },
      { text: '141. 数量', link: '/aip/general/0141_zh' },
      { text: '142. 时间与时长', link: '/aip/general/0142_zh' },
      { text: '143. 标准化代码', link: '/aip/general/0143_zh' },
      { text: '144. 重复字段', link: '/aip/general/0144_zh' },
      { text: '145. 范围', link: '/aip/general/0145_zh' },
      { text: '146. 通用字段', link: '/aip/general/0146_zh' },
      { text: '147. 敏感字段', link: '/aip/general/0147_zh' },
      { text: '148. 标准字段', link: '/aip/general/0148_zh' },
      { text: '149. 未设置的字段值', link: '/aip/general/0149_zh' },
      { text: '151. 长时运行操作', link: '/aip/general/0151_zh' },
      { text: '152. 作业', link: '/aip/general/0152_zh' },
      { text: '153. 导入与导出', link: '/aip/general/0153_zh' },
      { text: '154. 资源新鲜度校验', link: '/aip/general/0154_zh' },
      { text: '155. 请求标识', link: '/aip/general/0155_zh' },
      { text: '156. 单例资源', link: '/aip/general/0156_zh' },
      { text: '157. 部分响应', link: '/aip/general/0157_zh' },
      { text: '158. 分页', link: '/aip/general/0158_zh' },
      { text: '159. 跨集合读取', link: '/aip/general/0159_zh' },
      { text: '160. 过滤', link: '/aip/general/0160_zh' },
      { text: '161. 字段掩码', link: '/aip/general/0161_zh' },
      { text: '162. 资源修订版本', link: '/aip/general/0162_zh' },
      { text: '163. 变更校验', link: '/aip/general/0163_zh' },
      { text: '164. 软删除', link: '/aip/general/0164_zh' },
      { text: '165. 基于条件的删除', link: '/aip/general/0165_zh' },
      { text: '180. 向后兼容', link: '/aip/general/0180_zh' },
      { text: '181. 稳定性级别', link: '/aip/general/0181_zh' },
      { text: '182. 外部软件依赖', link: '/aip/general/0182_zh' },
      { text: '185. API 版本管理', link: '/aip/general/0185_zh' },
      { text: '190. 命名约定', link: '/aip/general/0190_zh' },
      { text: '191. 文件与目录结构', link: '/aip/general/0191_zh' },
      { text: '192. 文档', link: '/aip/general/0192_zh' },
      { text: '193. 错误', link: '/aip/general/0193_zh' },
      { text: '194. 自动重试配置', link: '/aip/general/0194_zh' },
      { text: '202. 字段', link: '/aip/general/0202_zh' },
      { text: '203. 字段行为文档', link: '/aip/general/0203_zh' },
      { text: '205. 阻断 Beta 发布的变更', link: '/aip/general/0205_zh' },
      { text: '210. Unicode', link: '/aip/general/0210_zh' },
      { text: '211. 授权校验', link: '/aip/general/0211_zh' },
      { text: '213. 通用组件', link: '/aip/general/0213_zh' },
      { text: '214. 资源过期', link: '/aip/general/0214_zh' },
      { text: '215. API 专用 proto', link: '/aip/general/0215_zh' },
      { text: '216. 状态', link: '/aip/general/0216_zh' },
      { text: '217. 不可达资源', link: '/aip/general/0217_zh' },
      { text: '231. 批量方法：Get', link: '/aip/general/0231_zh' },
      { text: '233. 批量方法：Create', link: '/aip/general/0233_zh' },
      { text: '234. 批量方法：Update', link: '/aip/general/0234_zh' },
      { text: '235. 批量方法：Delete', link: '/aip/general/0235_zh' },
      { text: '236. 策略预览', link: '/aip/general/0236_zh' },
    ],
  },
]

export default defineConfig({
  title: 'Fino Docs',
  description: 'API 规范与项目文档的中文知识库',
  cleanUrls: true,
  rewrites: {
    'generated/aip/general/:page.md': 'aip/general/:page.md',
  },
  // 官方英文源文件保留原站链接（/1、/general 等），镜像层不改写原文。
  ignoreDeadLinks: true,
  themeConfig: {
    siteTitle: 'AIPs 中文版',
    nav: [
      { text: 'AIPs', link: '/' },
      { text: '浏览 AIPs', link: '/aip/general' },
      { text: '动态', link: 'https://google.aip.dev/news' },
      { text: 'FAQ', link: 'https://google.aip.dev/faq' },
      { text: '参与贡献', link: 'https://google.aip.dev/contributing' },
      { text: 'API Linter ↗', link: 'https://linter.aip.dev/' },
      { text: 'GitHub ↗', link: 'https://github.com/aip-dev/google.aip.dev' },
      { component: 'LanguageSwitcher' },
      { component: 'ThemeSwitcher' },
    ],
    sidebar: {
      '/aip/general': generalSidebar,
      '/aip/': [
        {
          text: 'Google AIP 中文版',
          items: [
            { text: '总览', link: '/aip/' },
            { text: 'General：通用 AIP（72篇）', link: '/aip/general' },
            { text: '按 Scope 浏览', link: '/aip/scopes' },
            { text: '翻译与布局计划', link: '/aip/translation-plan' },
            { text: 'AIP-3：AIP 版本管理', link: '/aip/general/0003_zh' },
          ],
        },
        {
          text: 'Meta AIPs 1–99',
          collapsed: false,
          items: [
            { text: 'AIP-1：目的与指南', link: '/aip/general/0001_zh' },
            { text: 'AIP-2：编号', link: '/aip/general/0002_zh' },
            { text: 'AIP-3：版本管理', link: '/aip/general/0003_zh' },
            { text: 'AIP-8：风格与指导', link: '/aip/general/0008_zh' },
            { text: 'AIP-9：术语表', link: '/aip/general/0009_zh' },
          ],
        },
        {
          text: 'General 分类',
          collapsed: false,
          items: [
            { text: '元规范', link: '/aip/general#meta-元规范' },
            { text: '流程', link: '/aip/general#process-流程' },
            { text: 'API 概念', link: '/aip/general#api-concepts-api-概念' },
            { text: '资源设计', link: '/aip/general#resource-design-资源设计' },
            { text: '操作', link: '/aip/general#operations-操作' },
            { text: '字段', link: '/aip/general#fields-字段' },
            { text: '设计模式', link: '/aip/general#design-patterns-设计模式' },
            { text: '兼容性与版本管理', link: '/aip/general#compatibility-and-versioning-兼容性与版本管理' },
            { text: '润色', link: '/aip/general#polish-润色' },
            { text: 'Protocol Buffers', link: '/aip/general#protocol-buffers-protocol-buffers' },
            { text: '其他', link: '/aip/general#miscellaneous-其他' },
          ],
        },
      ],
      '/projects/': [
        {
          text: '项目文档',
          items: [{ text: '收录计划', link: '/projects/' }],
        },
      ],
    },
    search: { provider: 'local' },
    outline: { label: 'Categories', level: [2, 3] },
    docFooter: { prev: '上一篇', next: '下一篇' },
    lastUpdated: { text: '最后更新' },
    footer: {
      message: '为清晰而写',
      copyright: 'Fino Docs',
    },
    i18nRouting: false,
  },
})
